// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ===== WEB (Proyecto: tropical) =====
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl4WDw1SnIgnWkVLwVxrtqYBhzMu8VgvY', // ✅ Clave de API web
    appId:
        '<WEB_APP_ID>', // 🔴 Pega el App ID web (formato 1:439845573858:web:xxxxxxxx)
    messagingSenderId: '439845573858', // ✅ Project Number
    projectId: 'buses-f66da', // ✅ Project ID
    authDomain: 'buses-f66da.firebaseapp.com',
    storageBucket: 'buses-f66da.firebasestorage.app',
    measurementId: '<G-MEASUREMENT_ID>', // (opcional) si usas Analytics
  );

  // ===== ANDROID (com.mujerv.pasajero) =====
  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        '<ANDROID_API_KEY>', // 🔴 Toma de android/app/google-services.json → api_key.current_key
    appId:
        '1:439845573858:android:f0735de8d4f74a92e33abb', // ✅ App ID Android proporcionado
    messagingSenderId: '439845573858', // ✅
    projectId: 'buses-f66da', // ✅
    storageBucket: 'buses-f66da.firebasestorage.app',
  );

  // ===== iOS (no compartiste datos iOS; coloca los tuyos si corresponde) =====
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '<IOS_API_KEY>', // 🔴 De GoogleService-Info.plist → API_KEY
    appId:
        '<IOS_APP_ID>', // 🔴 De GoogleService-Info.plist → GOOGLE_APP_ID (1:439845573858:ios:xxxx)
    messagingSenderId: '439845573858', // ✅
    projectId: 'buses-f66da', // ✅
    storageBucket: 'buses-f66da.firebasestorage.app',
    iosBundleId: '<IOS_BUNDLE_ID>', // 🔴 Tu bundleId iOS (e.g., com.mav.app)
  );

  // ===== macOS (si usas macOS, suele compartir valores con iOS) =====
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '<IOS_API_KEY>', // 🔴
    appId: '<IOS_APP_ID>', // 🔴
    messagingSenderId: '439845573858',
    projectId: 'buses-f66da',
    storageBucket: 'buses-f66da.firebasestorage.app',
    iosBundleId: '<MACOS_BUNDLE_ID>', // 🔴 Tu bundleId de macOS si lo registras
  );

  // ===== Windows (si lo usas, suele usar credenciales tipo web) =====
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey:
        'AIzaSyDl4WDw1SnIgnWkVLwVxrtqYBhzMu8VgvY', // ✅ puedes reutilizar la web key
    appId:
        '<WEB_APP_ID_WINDOWS>', // 🔴 Un App ID web válido (o crea una app web dedicada)
    messagingSenderId: '439845573858',
    projectId: 'buses-f66da',
    authDomain: 'buses-f66da.firebaseapp.com',
    storageBucket: 'buses-f66da.firebasestorage.app',
    measurementId: '<G-MEASUREMENT_ID_WINDOWS>', // (opcional)
  );
}
